### ISSUE TITLE
TT decomposition error

### ISSUE THREAD

**Issue by Dimo0316** [rballester/tntorch#21]
When Irun the code in tntorch/tests/test_gpu.py of the tensor train decomposition, I get the error:  
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
How can I run the tt decomposition on GPU?

**Comment by rballester** [comment]
What is the full error dump for this problem?

**Comment by Dimo0316** [comment]
Dear rballester:
     This is the full error:
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    test_tt()
  File "test.py", line 11, in test_tt
    y2 =  tn.Tensor(X, ranks_tt=3, device=device).torch().cpu()
  File "/home/honghao/.local/lib/python3.6/site-packages/tntorch/tensor.py", line 276, in __init__
    self.round_tt(rmax=ranks_tt, algorithm=algorithm)
  File "/home/honghao/.local/lib/python3.6/site-packages/tntorch/tensor.py", line 1502, in round_tt
    delta = eps/max(1, torch.sqrt(torch.tensor([N-1], dtype=torch.float64)))*torch.norm(self.cores[-1])
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
     Thanks.

**Comment by rballester** [comment]
The error doesn't reproduce on my

**Comment by Dimo0316** [comment]
Thanks so much, your test code is full right. I got this error because of the wrong generation of the tensor.
