### ISSUE TITLE
How do I see the tensor data after decomposition?

### ISSUE THREAD

**Issue by GlazeDonuts** [rballester/tntorch#26]
Consider,
```a = torch.randn(2, 3, 4)```
```b = tn.Tensor(a, ranks_cp=2)```

If I want to view the values of the approximated tensor `b`, how do I do that? Can I get a numpy array or torch tensor like `a`? Since I need to perform operations like element-wise subtraction between the true tensor and approximated one.

**Comment by Aelphy** [comment]
You can call b.torch()

**Comment by GlazeDonuts** [comment]
Thanks a lot :)
