### ISSUE TITLE
tutorials/active_subspaces.ipynb   error

### ISSUE THREAD

**Issue by ZhihengCV** [rballester/tntorch#38]
![image](https://user-images.githubusercontent.com/9738274/190042681-7d705fca-ead9-40e0-8351-e87ff2031c06.png)

![image](https://user-images.githubusercontent.com/9738274/190042768-fff8cbb6-1087-4b00-b0b3-953ed9250382.png)

**Comment by Aelphy** [comment]
The second error I couldn't reproduce. The first error is fixe with the upcoming PR. Please update your tntorch from GitHub after it is accepted
