### ISSUE TITLE
Default dtype float64

### ISSUE THREAD

**Issue by lopsided** [rballester/tntorch#4]
Hi,

I was playing around with this library in my project and kept getting some strange behaviour. It took me a while to track it down but it seems to be caused by this line;

`torch.set_default_dtype(torch.float64)`
https://github.com/VMML/tntorch/blob/8c81a1cbb0c5b19db7c26a787acfca35e0fbd960/tntorch/tensor.py#L4

Which is called upon importing tntorch. Is this line really necessary since it does have knock on effects when incorporating tntorch into existing torch projects?

Thanks for the great library.
Tom

**Comment by rballester** [comment]
Hi Tom,

Agreed, I've removed the line in 18719403081cab00560ee9ab2d523fb7c577f08a.
