### ISSUE TITLE
Tensor indices

### ISSUE THREAD

**Issue by rafaeleb** [rballester/tntorch#42]
Hello all,

I am just starting to use the library, and I am wondering if there is a way to specify tensor indices with labels or tags, and to perform contractions according to these tags. 

BR,

Rafael

**Comment by rballester** [comment]
Hi Rafael, are you referring to something like PyTorch's named tensors (https://pytorch.org/docs/stable/named_tensor.html)? tntorch does not support that currently, but you might want to take a look at the _quimb_ package for contraction of general tensor networks along specified tags (https://quimb.readthedocs.io/en/latest/autoapi/quimb/tensor/tensor_core/index.html#quimb.tensor.tensor_core.tensor_contract)

**Comment by rafaeleb** [comment]
Hi Rafael,

Thanks for the reply. I was aware of the possibility of doing that in quimb. I will have another look at that.
